services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ..:/content-manager
    env_file:
      - ../.env
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: postgres:17-bookworm
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    env_file:
      - ../.env
    restart: always
volumes:
  postgres-db: